### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Thanh-Binh** [PeterOvermann/TriadicMemory#6]
Hi
I am testing the algorithm TriadicMemory in C as follows
       int N = 1000, P=10;
       TriadicMemory *T = triadicmemory_new(N, P);
    	
	SDR *x = sdr_new(N);
	SDR *y = sdr_new(N);
	SDR *z = sdr_new(N);
	
	int ax[3] = {1, 2, 3};
	x->a = ax;
	x->p = 3;	// length of a

	int ay[3] = {4, 5 ,6};
	y->a = ay;
	y->p = 3;	// length of a

	int az[3] = {7, 8, 9};
	z->a = az;
	z->p = 3;	// length of a

	triadicmemory_write  (T, x, y, z);

	SDR *xx = sdr_new(N);
	xx->p == -1; // read x
	sdr_print( triadicmemory_read_x (T, xx, y, z));

and in the consol terminal I get results for x
2 3 4
I expected the results like [1 2 3]
Is it a bug here?
Thanks

**Comment by Thanh-Binh** [comment]
it is a bug in the function sdr_print(), I found

**Comment by PeterOvermann** [comment]
Not a bug. The internal representation uses values from 0 to N-1. The command line interfaces uses values from 1 to N.
I added comments in sdr_print() and parse() to clarify.

**Comment by Thanh-Binh** [comment]
@PeterOvermann I do not understand because the Input are value from 1 to 9, where N=1000. it must return the value of x I inputted (1 2 3) and not (2 3 4) like you commented

**Comment by PeterOvermann** [comment]
Your input was directly into the internal representation, not via the command line parser which subtracts 1 from each value.
You can use the following function to print the internal representation with values 0 to N-1:

void sdr_print_internal (SDR *s) // print sdr positions in the range 0 to N-1
	{
	for (int r = 0; r < s->p; r++)
		{
		printf("%d", s->a[r]);  
		if (r < s->p -1) printf(" ");
		}
	printf("\n"); fflush(stdout);
	}

**Comment by Thanh-Binh** [comment]
Thanks . It is exactly what I found and did in my version.But I believe that we have to modify parse() so it outputs x, y, z correctly from what the user inputed Gesendet mit der mobilen Mail AppAm 27.07.22 um 10:52 schrieb Peter Overmann
                
            
            
                
                    Von: "Peter Overmann" ***@***.***>Datum: 27. Juli 2022An: "PeterOvermann/TriadicMemory" ***@***.***>Cc: "Thanh-Binh" ***@***.***>,"Author" ***@***.***>Betreff: Re: [PeterOvermann/TriadicMemory] bug (Issue #6)
                
                
Your input was directly into the internal representation, not via the command line parser which subtracts 1 from each value.
You can use the following function to print the internal representation with values 0 to N-1:
void sdr_print_internal (SDR *s) // print sdr positions in the range 0 to N-1
{
for (int r = 0; r < s->p; r++)
{
printf("%d", s->a[r]);
if (r < s->p -1) printf(" ");
}
printf("\n"); fflush(stdout);
}

**Comment by PeterOvermann** [comment]
parse() is doing the right thing: it converts from the 1..N convention used in command line input to the C-internal convention 0..N-1. sdr_print() does the reverse conversion.
